name: build pull request

on:
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    name: Build the article PDF
    concurrency: showyourwork-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build the article PDF
        id: build
        with:
          showyourwork-spec: git+https://github.com/showyourwork/showyourwork
          conda-cache-number:
        uses: HealthyPear/showyourwork-action@tests
        env:
          SANDBOX_TOKEN: ${{ secrets.SANDBOX_TOKEN }}
          OVERLEAF_TOKEN: ${{ secrets.OVERLEAF_TOKEN }}
